# Generated by Django 4.1.2 on 2022-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug_prof', models.SlugField()),
                ('prenoms', models.CharField(max_length=70)),
                ('matricule', models.CharField(max_length=255, unique=True)),
                ('grade', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('actifs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
