# Generated by Django 4.1.2 on 2022-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='image',
            field=models.ImageField(default='media/professor/default.png', upload_to='media/professor/'),
        ),
    ]
