# Generated by Django 4.1.2 on 2022-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(default='media/images/default.png', upload_to='media/student/'),
        ),
    ]
