# Generated by Django 4.1.2 on 2022-11-10 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etudiant', '0002_etudiant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Etudiants'},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='matricule',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('niveau 1', 'niveau 1'), ('niveau 2', 'niveau 2'), ('niveau 3', 'niveau 3'), ('niveau 4', 'niveau 4'), ('niveau 5', 'niveau 5'), ('niveau 6', 'niveau 6')], default='niveau 1', max_length=50),
        ),
    ]
