# Generated by Django 4.1.2 on 2022-11-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
        ('professeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('intitule', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeur.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=255)),
                ('critere', models.CharField(max_length=255)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ue')),
            ],
        ),
    ]
