# Generated by Django 4.1.2 on 2022-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=255, unique=True)),
                ('grade', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_enregistrment', models.DateTimeField()),
            ],
        ),
    ]
